"""
report_generator.py - Generates a polished PDF Executive Brief
from the structured Gemini analysis dict.
"""

import os
import json
from datetime import datetime
from fpdf import FPDF, XPos, YPos
from colorama import Fore, Style

import config

# --- Colour Palette ---
NAVY   = (10,  36,  99)
TEAL   = (0,  128, 128)
GREY   = (80,  80,  80)
LGREY  = (245, 245, 245)
WHITE  = (255, 255, 255)
BLACK  = (20,  20,  20)
RED    = (192,  0,   0)
AMBER  = (255, 153,  0)
GREEN  = (0,  153,  76)

SEVERITY_COLOR = {"critical": RED, "high": AMBER, "medium": (0, 102, 204), "low": GREEN}
IMPACT_COLOR = {"high": RED, "medium": AMBER, "low": GREEN}

class ExecutiveBriefPDF(FPDF):
    def __init__(self, topic: str):
        super().__init__("P", "mm", "A4")
        self.topic    = topic
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)
        self.add_font_family()

    def add_font_family(self):
        pass

    def header(self):
        if self.page_no() == 1: return
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 12, "F")
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 8)
        self.set_xy(10, 3)
        self.cell(0, 6, f"EXECUTIVE BRIEF  |  {self.topic.upper()}", align="L")
        self.set_xy(10, 3)
        self.cell(0, 6, f"CONFIDENTIAL  |  Page {self.page_no()}", align="R")
        self.set_text_color(*BLACK)
        self.ln(14)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GREY)
        self.cell(0, 10, f"Generated by Market Research Engine  *  {datetime.now():%d %b %Y}", align="C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(*NAVY)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, f"  {title.upper()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
        self.ln(2)
        self.set_text_color(*BLACK)

    def body_text(self, text: str, indent: int = 0):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*GREY)
        self.set_x(self.get_x() + indent)
        self.multi_cell(0, 5, text)
        self.ln(1)
        self.set_text_color(*BLACK)

    def badge(self, label: str, color: tuple):
        self.set_fill_color(*color)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 7)
        self.cell(18, 5, label.upper(), align="C", fill=True)
        self.set_text_color(*BLACK)

    def kv_row(self, key: str, value: str, shade: bool = False):
        if shade: self.set_fill_color(*LGREY)
        self.set_font("Helvetica", "B", 9)
        self.cell(55, 6, key, fill=shade)
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 6, value, fill=shade)
        self.ln(0)

    def divider(self):
        self.set_draw_color(*TEAL)
        self.set_line_width(0.3)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(3)

    def cover_page(self, analysis: dict):
        self.add_page()
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 60, "F")
        self.set_fill_color(*TEAL)
        self.rect(0, 60, 210, 5, "F")
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 22)
        self.set_xy(20, 15)
        self.cell(0, 12, "EXECUTIVE BRIEF", align="C")
        self.set_font("Helvetica", "B", 14)
        self.set_xy(20, 30)
        self.cell(0, 10, self.topic, align="C")
        self.set_font("Helvetica", "", 10)
        self.set_xy(20, 44)
        self.cell(0, 8, f"AI-Powered Market Research Report", align="C")
        self.set_text_color(*BLACK)
        self.set_xy(20, 75)
        self.set_fill_color(*LGREY)
        self.set_draw_color(*TEAL)
        self.set_line_width(0.5)
        self.rect(20, 75, 170, 40, "FD")

        meta = [
            ("Date Generated",  datetime.now().strftime("%d %B %Y, %H:%M")),
            ("Articles Analysed", str(analysis.get("articles_used", "-"))),
            ("Date Range",      f"{analysis.get('date_range', {}).get('from','-')}  to  {analysis.get('date_range', {}).get('to','-')}"),
            ("Sources",         ", ".join(analysis.get("sources", [])[:5])),
            ("Confidence Score", f"{analysis.get('confidence_score', 0):.0%}"),
            ("Sentiment",       f"{analysis.get('sentiment_score', 0):+.2f}  (-1 = very negative, +1 = very positive)"),
        ]
        self.set_xy(25, 78)
        for k, v in meta:
            self.set_font("Helvetica", "B", 8)
            self.set_x(25)
            self.cell(45, 6, k + ":")
            self.set_font("Helvetica", "", 8)
            self.cell(0, 6, v[:90], new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self.set_xy(20, 120)
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(*GREY)
        self.multi_cell(170, 4,
            "CONFIDENTIAL - This brief was automatically synthesised by an AI-powered research engine. "
            "All findings are derived from publicly available RSS feeds and should be validated against "
            "primary sources before strategic decision-making."
        )
        self.set_text_color(*BLACK)

def _write_executive_summary(pdf: ExecutiveBriefPDF, analysis: dict):
    pdf.section_title("1. Executive Summary")
    pdf.body_text(analysis.get("executive_summary", "No summary available."))
    pdf.divider()

def _write_trends(pdf: ExecutiveBriefPDF, analysis: dict):
    pdf.section_title("2. Key Market Trends")
    trends = analysis.get("key_trends", [])
    for i, t in enumerate(trends, 1):
        shade = (i % 2 == 0)
        impact = t.get("impact", "Medium").lower()
        color  = IMPACT_COLOR.get(impact, IMPACT_COLOR["medium"])
        pdf.set_fill_color(*(LGREY if shade else WHITE))
        pdf.set_x(20)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, f"  Trend {i}: {t.get('trend','')}", fill=shade, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_x(20)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GREY)
        pdf.cell(35, 5, "  Evidence:", fill=shade)
        pdf.multi_cell(0, 5, t.get("evidence", "-"), fill=shade)
        pdf.set_x(20)
        pdf.set_text_color(*BLACK)
        pdf.cell(35, 5, "  Impact:", fill=shade)
        pdf.badge(t.get("impact", "Medium"), color)
        pdf.ln(6)
    pdf.divider()

def _write_risks(pdf: ExecutiveBriefPDF, analysis: dict):
    pdf.section_title("3. Risk Factors & Challenges")
    risks = analysis.get("risk_factors", [])
    for i, r in enumerate(risks, 1):
        sev   = r.get("severity", "Medium").lower()
        color = SEVERITY_COLOR.get(sev, SEVERITY_COLOR["medium"])
        shade = (i % 2 == 0)
        fill  = LGREY if shade else WHITE
        pdf.set_fill_color(*fill)
        pdf.set_x(20)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, f"  Risk {i}: {r.get('risk','')}", fill=shade, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_x(20)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GREY)
        pdf.cell(35, 5, "  Severity:", fill=shade)
        pdf.set_text_color(*BLACK)
        pdf.badge(r.get("severity", "Medium"), color)
        pdf.ln(5)
        pdf.set_x(20)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GREY)
        pdf.cell(35, 5, "  Mitigation:", fill=shade)
        pdf.set_text_color(*BLACK)
        pdf.set_font("Helvetica", "", 8)
        pdf.multi_cell(0, 5, r.get("mitigation", "-"), fill=shade)
        pdf.ln(2)
    pdf.divider()

def _write_bottlenecks(pdf: ExecutiveBriefPDF, analysis: dict):
    pdf.section_title("4. Operational Bottlenecks")
    bns = analysis.get("operational_bottlenecks", [])
    for i, b in enumerate(bns, 1):
        shade = (i % 2 == 0)
        fill  = LGREY if shade else WHITE
        pdf.set_fill_color(*fill)
        pdf.set_x(20)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, f"  {i}. {b.get('bottleneck','')}", fill=shade, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_x(20)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GREY)
        pdf.cell(40, 5, "  Affected Area:", fill=shade)
        pdf.set_text_color(*BLACK)
        pdf.multi_cell(0, 5, b.get("affected_area", "-"), fill=shade)
        pdf.set_x(20)
        pdf.set_text_color(*GREY)
        pdf.cell(40, 5, "  Recommendation:", fill=shade)
        pdf.set_text_color(*BLACK)
        pdf.set_font("Helvetica", "I", 8)
        pdf.multi_cell(0, 5, b.get("recommendation", "-"), fill=shade)
        pdf.ln(2)
    pdf.divider()

def _write_competitive(pdf: ExecutiveBriefPDF, analysis: dict):
    pdf.section_title("5. Competitive Landscape")
    cl = analysis.get("competitive_landscape", {})
    pdf.body_text(cl.get("summary", "No data available."))
    players = cl.get("key_players", [])
    if players:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, "Key Players Identified:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 8)
        x_start = pdf.get_x()
        for p in players:
            if pdf.get_x() + 40 > 190:
                pdf.ln(7)
                pdf.set_x(x_start)
            pdf.set_fill_color(*TEAL)
            pdf.set_text_color(*WHITE)
            pdf.cell(max(len(p)*2+6, 20), 6, f" {p} ", fill=True)
            pdf.cell(2, 6, "")
        pdf.ln(8)
        pdf.set_text_color(*BLACK)
    pdf.divider()

def _write_recommendations(pdf: ExecutiveBriefPDF, analysis: dict):
    pdf.section_title("6. Strategic Recommendations")
    recs = analysis.get("strategic_recommendations", [])
    for r in recs:
        p = r.get("priority", "-")
        tl = r.get("timeline", "Medium term")
        tl_color = {"short term": GREEN, "medium term": AMBER, "long term": RED}
        c = tl_color.get(tl.lower(), AMBER)
        pdf.set_fill_color(*LGREY)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_x(20)
        pdf.cell(8, 7, f"  #{p}", fill=True)
        pdf.cell(0, 7, f"  {r.get('action','')}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_x(28)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GREY)
        pdf.cell(28, 5, "Rationale:")
        pdf.set_text_color(*BLACK)
        pdf.multi_cell(0, 5, r.get("rationale", "-"))
        pdf.set_x(28)
        pdf.set_text_color(*GREY)
        pdf.cell(28, 5, "Timeline:")
        pdf.set_text_color(*BLACK)
        pdf.badge(tl, c)
        pdf.ln(7)
    pdf.divider()

def _write_conclusion(pdf: ExecutiveBriefPDF, analysis: dict):
    pdf.section_title("7. Conclusion")
    sent = analysis.get("sentiment_score", 0)
    conf = analysis.get("confidence_score", 0)
    outlook = "positive" if sent > 0.1 else ("negative" if sent < -0.1 else "neutral")
    conclusion = (
        f"Based on the analysis of {analysis.get('articles_used', '?')} articles from "
        f"{len(analysis.get('sources',[]))} sources, the overall market sentiment for "
        f"'{analysis.get('topic','')}' is {outlook} (score: {sent:+.2f}). "
        f"The research engine's confidence in coverage quality is {conf:.0%}. "
        f"Leadership is advised to prioritise the top-ranked strategic recommendations "
        f"and monitor the identified risk factors on an ongoing basis."
    )
    pdf.body_text(conclusion)

def generate_report(analysis: dict, output_dir: str = None) -> str:
    output_dir = output_dir or config.OUTPUT_DIR
    os.makedirs(output_dir, exist_ok=True)
    topic     = analysis.get("topic", "Market Research")
    safe_name = topic.lower().replace(" ", "_")[:40]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pdf_path  = os.path.join(output_dir, f"executive_brief_{safe_name}_{timestamp}.pdf")
    
    print(f"\n{Fore.CYAN}{'-'*60}")
    print(f"  📄  REPORT GENERATOR  |  Building Executive Brief...")
    print(f"{'-'*60}{Style.RESET_ALL}")
    
    pdf = ExecutiveBriefPDF(topic=topic)
    pdf.cover_page(analysis)
    
    pdf.add_page()
    _write_executive_summary(pdf, analysis)
    _write_trends(pdf, analysis)
    _write_risks(pdf, analysis)
    
    pdf.add_page()
    _write_bottlenecks(pdf, analysis)
    _write_competitive(pdf, analysis)
    _write_recommendations(pdf, analysis)
    _write_conclusion(pdf, analysis)
    
    pdf.output(pdf_path)
    print(f"  {Fore.GREEN}✔  PDF saved:{Style.RESET_ALL} {pdf_path}\n")
    
    json_path = pdf_path.replace(".pdf", "_raw_analysis.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(analysis, f, indent=2, ensure_ascii=False)
    print(f"  {Fore.GREEN}✔  JSON saved:{Style.RESET_ALL} {json_path}\n")
    
    return pdf_path